Add iter5
rybalka1/devmetrics pull request #5
Opened 2024-03-17 18:11 UTC by rybalka1

2024-03-19 23:37 UTC, avhitrov requested changes
На все основные ошибки указал в комментариях к коду. Резюмируя:
1. Неверно реализована отправка счетчика.
2. Ошибки в формировании http-ответа
3. Гонки данны (DATA RACE) при одновременном сохранении и чтении метрик
4. Тикеры необходимо останавливать

В остальном код хороший. Жду исправления недочетов.

2024-03-19 23:37 UTC, avhitrov commented on cmd/agent/main.go
> +		return
```suggestion
		log.Fatal(err)
```

2024-03-19 23:37 UTC, avhitrov commented on internal/agent/agent.go
> +	reportTicker := time.NewTicker(agent.reportInterval)
Тикеры по завершении необходимо останавливать. Даже в таком вырожденном случае очень желательно дернуть
```
defer func() {
    pollTicker.Stop()
    reportTicker .Stop()
}()
```

2024-03-19 23:37 UTC, avhitrov commented on internal/agent/agent.go
> +	}
После успешной отправки необходимо сбрасывать PollCount, иначе на сервере будет собираться лишенная смысла геометрическая прогрессия. А должно быть монотонно возрастающее значение, соответствующее количеству циклов сбора данных, проделанных агентом.

2024-03-19 23:37 UTC, avhitrov commented on internal/memstorage/memstorage.go
> +	dataGauges   map[string]float64
Мапы не являются потокобезопасными структурами данных. Поэтому при работе с ними (чтение-запись) в многопоточном приложении (а http-сервер по определению таковым является) необходимо защищать их блокировкой. В go для этого используются мьютексы: Mutex и RWMutex. Подробнее: https://t.me/bushigo/24

В данном приложении ловим DATA RACE (скомпилировать с ключом -race и бомбить одновременно агентом и запросами на чтение данных):
```
==================
WARNING: DATA RACE
Write at 0x00c000088a80 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  github.com/rybalka1/devmetrics/internal/memstorage.(*MemStorage).UpdateCounters()
      C:/work/src/github.com/rybalka1/devmetrics/internal/memstorage/memstorage.go:52 +0x95
  github.com/rybalka1/devmetrics/internal/handlers.NewRouter.func1.UpdateCounterHandle.func1()
      C:/work/src/github.com/rybalka1/devmetrics/internal/handlers/handlers.go:81 +0xaa
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/rybalka1/devmetrics/internal/handlers.printMidl.func1()
      C:/work/src/github.com/rybalka1/devmetrics/internal/handlers/router.go:33 +0xf7
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:73 +0x6f4
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Previous read at 0x00c000088a80 by goroutine 2248:
  runtime.mapaccess2_faststr()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map_faststr.go:108 +0x0
  github.com/rybalka1/devmetrics/internal/memstorage.MemStorage.GetMetric()
      C:/work/src/github.com/rybalka1/devmetrics/internal/memstorage/memstorage.go:68 +0x14d
  github.com/rybalka1/devmetrics/internal/memstorage.(*MemStorage).GetMetric()
      <autogenerated>:1 +0x7d
  github.com/rybalka1/devmetrics/internal/handlers.NewRouter.func2.GetMetric.func1()
      C:/work/src/github.com/rybalka1/devmetrics/internal/handlers/handlers.go:91 +0x95
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:73 +0x6f4
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  github.com/rybalka1/devmetrics/internal/server.(*MetricServer).Start()
      C:/work/src/github.com/rybalka1/devmetrics/internal/server/server.go:51 +0xe4
  main.main()
      C:/work/src/github.com/rybalka1/devmetrics/cmd/server/main.go:33 +0x127

Goroutine 2248 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  github.com/rybalka1/devmetrics/internal/server.(*MetricServer).Start()
      C:/work/src/github.com/rybalka1/devmetrics/internal/server/server.go:51 +0xe4
  main.main()
      C:/work/src/github.com/rybalka1/devmetrics/cmd/server/main.go:33 +0x127
==================
```

2024-03-19 23:37 UTC, avhitrov commented on internal/handlers/handlers.go
> +		rw.WriteHeader(http.StatusOK)
Вот здесь сервер ругаецца!
```
http: superfluous response.WriteHeader call from github.com/rybalka1/devmetrics/internal/handlers.NewRouter.func2.GetMetric.func1 (handlers.go:103)
```
Это происходит из-за неверной последовательности выдачи http-содержимого клиенту.
1. Сначала производятся все операции над элементами http-заголовка
2. Потом отдается WriteHeader и устанавливает код ответа
3. Только потом пишется тело http-ответа (rw.Write)
Если тело каким-то образом записано, то данный фреймворк сам формирует какой-то дефолтный ответ, закрывает заголовок и ругается на все попытки еще раз протолкнуть код ответа.

2024-04-02 21:38 UTC, avhitrov requested changes
Не до конца исправлены гонки. Не решена проблема `superfluous response.WriteHeader call`. Счетчик все еще растет в геометрической прогрессии.

2024-04-02 21:38 UTC, avhitrov commented on internal/handlers/handlers.go
> +		rw.WriteHeader(http.StatusOK)
Не исправлено, стало только хуже. Теперь в случае возникновения ошибки после записи тела сервер попытается выставить сразу два статуса. Верное исправление – `_, err := rw.Write([]byte(value))` переставить ниже по коду, чем `rw.WriteHeader(http.StatusOK)`. Если в Write возникает ошибка - ее просто игнорировать.

2024-04-02 21:38 UTC, avhitrov commented on internal/memstorage/memstorage.go
> +	muGauges     sync.RWMutex
Достаточно одного мьютекса. Иначе в процедуре GetMetric придется взводить оба, чтобы не попасть на гонки по счетчику.

2024-04-02 21:38 UTC, avhitrov commented on internal/memstorage/memstorage.go
> +	defer ms.muGauges.Unlock()
Если в данной функции будет затребована метрика типа счетчик, и одновременно другой хендлер будет изменять счетчик, гонки все равно возникнут. Необходимо либо использовать один мьютекс на все, либо поместить `Lock` и `defer Unlock` внутрь `case` и дергать внутри уже соответствующий мьютекс. 

КМК единый мьютекс будет надежней. Если есть сомнения по быстродействию, рекомендую использовать для чтения пару `RLock-RUnlock`.

2024-04-07 14:34 UTC, rybalka1 commented on internal/memstorage/memstorage.go
> +	muGauges     sync.RWMutex
Пожалуйста пиши в следующий раз чем и как происходит тестирование, чтобы я в следующий раз мог у себя всё это воспроизвести и увидеть сам, это сильно мне поможет увидеть то же самое. Для меня пока всё это не очевидно, потому, что в первую очередь ориентируюсь на автотесты. По логике авторов текста курса, если атотесты прошли, значит код работает как нужно. Спасибо.

2024-04-08 22:40 UTC, avhitrov commented on internal/memstorage/memstorage.go
> +	muGauges     sync.RWMutex
Не вопрос. Я компилирую обе компоненты с ключом `-race` и запускаю одновременно в двух окнах powershell. Одновременно запускаю вот такой скрипт:
```
#!/bin/bash

for ROW in {1..10000}
do
   curl -s -X GET http://192.168.126.1:8080/value/counter/PollCount
done
```
И смотрю на вывод компонент.

И еще - я хорошо знаю логику авторов курса. И эта логика заключается в том, чтобы научить будущих программистов на Go не косячить. Автотесты позволяют проверить самые очевидные ошибки. Гонки данных ими проверить невозможно. Зачастую соответствие кода заданию - тоже. Поэтому и существует проверка ПР ментором (или ревьюером).

2024-04-08 22:55 UTC, avhitrov commented on internal/agent/agent.go
> +	}
Счетчик все еще растет в геометрической прогрессии. Тестировать так же, как описано: одновременный запуск сервер и агента, проверка через интервалы времени в браузере `http://localhost:8080/value/counter/PollCount`

2024-04-08 22:57 UTC, avhitrov requested changes
Почти все замечания исправлены. Остался счетчик, который растет в геометрической прогрессии.

2024-04-11 06:17 UTC, rybalka1 commented on internal/agent/agent.go
> +	}
Большое спасибо за обратную связь. Понимание как проходит тестирование сильно облегчает поиск ошибок.

2024-04-11 21:56 UTC, avhitrov requested changes
Все еще счетчик!

2024-04-11 21:56 UTC, avhitrov commented on internal/agent/agent.go
> +	}
Не здесь следует обнулять метрику, а после цикла `for` в SendMetrics (если не возникла ошибка). Кстати, при `err != nil` в результате `http.Post` можно смело вызывать `return`. 

Самый простой способ тестирования - запустить штатно агент и сервер и в браузере смотреть на строку 
```http://localhost:8080/value/counter/PollCount```
Раз в 10 секунд значение должно увеличиваться на 5 (между двумя отправками умещается 5 проходов). Флуктуации возможны и не являются чем-то ошибочным, но общий тренд такой.

2024-04-14 18:44 UTC, rybalka1 commented on internal/agent/agent.go
> +	}
Да, мой косяк. Перечитал ещё раз задания и нашел, что этот момент отдельно оговаривался.
https://www.youtube.com/watch?v=IN-odS5Eki0  😂

2024-04-16 22:55 UTC, avhitrov approved these changes
Все. Принято!

2024-04-17 08:13 UTC, merged